trigger:
- main

pool:
  vmImage: 'macos-13'

steps:
- script: /bin/bash -c "sudo xcode-select -s /Applications/Xcode_15.0.1.app/Contents/Developer"
  displayName: 'Select Xcode 15'

- script: |
    dotnet tool install --global boots
    boots --stable Xamarin.iOS

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '5.0.400'

- script: |
    dotnet restore

- task: XamariniOS@2
  inputs:
    solutionFile: '**/*.iOS.csproj'
    configuration: 'Release'
    buildForSimulator: true
    packageApp: false
